# Generated by Django 3.1 on 2022-01-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='listinng',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='active',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creator_user',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='update_time',
        ),
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting goods'), ('HW', 'Health & Wellness'), ('PS', 'Pets supplies')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
        migrations.DeleteModel(
            name='Bid',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
