# Generated by Django 3.1 on 2022-01-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20220104_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='listing',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='name'),
        ),
    ]
