# Generated by Django 3.1 on 2022-01-05 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_auto_20220104_2046'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting goods'), ('HW', 'Health & Wellness'), ('PS', 'Pets supplies')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='creation_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='creator_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='update_time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
