# Generated by Django 3.1 on 2022-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_remove_listing_creation_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creation_time',
            field=models.DateField(default=None),
        ),
    ]
