# Generated by Django 3.1 on 2022-01-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_creation_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='creation_time',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='creator_user',
        ),
        migrations.AlterField(
            model_name='listing',
            name='active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
