# Generated by Django 3.1 on 2022-01-05 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auto_20220105_1419'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creation_time',
            field=models.DateField(default=None, null=True),
        ),
    ]
