# Generated by Django 3.1 on 2022-01-05 15:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listing_creation_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creation_time',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
