# Generated by Django 3.1 on 2022-01-05 15:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_listing_creator_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creator_user',
            field=models.ForeignKey(default='User', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
