# Generated by Django 3.1 on 2022-01-05 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_auto_20220105_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='creator_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.user'),
            preserve_default=False,
        ),
    ]
