# Generated by Django 3.1 on 2022-01-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0029_auto_20220105_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='creator_user',
        ),
        migrations.AddField(
            model_name='listing',
            name='update_time',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
