# Generated by Django 3.1 on 2022-01-05 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0030_auto_20220105_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='creator_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='auctions.user'),
            preserve_default=False,
        ),
    ]
