# Generated by Django 3.1 on 2022-01-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0032_auto_20220107_0026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting goods'), ('HW', 'Health & Wellness'), ('PS', 'Pets supplies'), ('CG', 'Children’s goods')], default='Shit', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
