# Generated by Django 3.1 on 2022-01-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourites',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
