# Generated by Django 3.1.2 on 2022-01-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0041_listing_buyer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[], max_length=50),
        ),
    ]
