# Generated by Django 3.1.2 on 2022-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0042_auto_20220120_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Fashion', 'FA'), ('Consumer Electronics', 'CE'), ('Sporting goods', 'SG'), ('Health & Wellness', 'HW'), ('Pets supplies', 'PS'), ('Children’s goods', 'CG')], max_length=50),
        ),
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
