# Generated by Django 3.1.2 on 2022-01-22 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0043_auto_20220122_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='note',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
