# Generated by Django 3.1.2 on 2022-01-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0044_auto_20220122_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='note',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
