# Generated by Django 3.1.2 on 2022-01-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0045_auto_20220123_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='starting_bid',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
