# Generated by Django 4.0.1 on 2022-01-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0046_auto_20220123_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('FA', 'Fashion'), ('CE', 'Consumer Electronics'), ('SG', 'Sporting goods'), ('Health & Wellness', 'HW'), ('Pets supplies', 'PS'), ('Children’s goods', 'CG')], max_length=50),
        ),
    ]
